import type { Person } from '@/hooks/useElevatorSimulation';

// This manifest defines a fixed sequence of passenger arrivals for the competition.
// Every simulation run will use this exact same data, ensuring fairness.
// - id: Unique identifier for the person.
// - spawnTime: The simulation tick at which the person appears.
// - originFloor: The floor where the person starts waiting.
// - destinationFloor: The floor the person wants to go to.
export const PASSENGER_MANIFEST: Omit<Person, 'pickupTime'>[] = [
  { id: 1, spawnTime: 2, originFloor: 3, destinationFloor: 8 },
  { id: 2, spawnTime: 5, originFloor: 0, destinationFloor: 9 },
  { id: 3, spawnTime: 8, originFloor: 7, destinationFloor: 1 },
  { id: 4, spawnTime: 10, originFloor: 5, destinationFloor: 0 },
  { id: 5, spawnTime: 12, originFloor: 2, destinationFloor: 6 },
  { id: 6, spawnTime: 15, originFloor: 9, destinationFloor: 4 },
  { id: 7, spawnTime: 18, originFloor: 1, destinationFloor: 7 },
  { id: 8, spawnTime: 20, originFloor: 6, destinationFloor: 3 },
  { id: 9, spawnTime: 23, originFloor: 8, destinationFloor: 0 },
  { id: 10, spawnTime: 25, originFloor: 4, destinationFloor: 9 },
  { id: 11, spawnTime: 28, originFloor: 0, destinationFloor: 5 },
  { id: 12, spawnTime: 31, originFloor: 9, destinationFloor: 2 },
  { id: 13, spawnTime: 34, originFloor: 3, destinationFloor: 7 },
  { id: 14, spawnTime: 36, originFloor: 6, destinationFloor: 1 },
  { id: 15, spawnTime: 39, originFloor: 2, destinationFloor: 8 },
  { id: 16, spawnTime: 42, originFloor: 7, destinationFloor: 0 },
  { id: 17, spawnTime: 45, originFloor: 1, destinationFloor: 9 },
  { id: 18, spawnTime: 48, originFloor: 8, destinationFloor: 3 },
  { id: 19, spawnTime: 50, originFloor: 4, destinationFloor: 6 },
  { id: 20, spawnTime: 53, originFloor: 5, destinationFloor: 2 },
  { id: 21, spawnTime: 56, originFloor: 9, destinationFloor: 0 },
  { id: 22, spawnTime: 59, originFloor: 0, destinationFloor: 7 },
  { id: 23, spawnTime: 62, originFloor: 6, destinationFloor: 4 },
  { id: 24, spawnTime: 65, originFloor: 3, destinationFloor: 1 },
  { id: 25, spawnTime: 68, originFloor: 8, destinationFloor: 5 },
  { id: 26, spawnTime: 71, originFloor: 2, destinationFloor: 9 },
  { id: 27, spawnTime: 74, originFloor: 7, destinationFloor: 3 },
  { id: 28, spawnTime: 77, originFloor: 1, destinationFloor: 6 },
  { id: 29, spawnTime: 80, originFloor: 9, destinationFloor: 1 },
  { id: 30, spawnTime: 83, originFloor: 4, destinationFloor: 0 },
  { id: 31, spawnTime: 86, originFloor: 0, destinationFloor: 8 },
  { id: 32, spawnTime: 89, originFloor: 5, destinationFloor: 3 },
  { id: 33, spawnTime: 92, originFloor: 8, destinationFloor: 2 },
  { id: 34, spawnTime: 95, originFloor: 3, destinationFloor: 9 },
  { id: 35, spawnTime: 98, originFloor: 6, destinationFloor: 0 },
  { id: 36, spawnTime: 101, originFloor: 1, destinationFloor: 5 },
  { id: 37, spawnTime: 104, originFloor: 7, destinationFloor: 4 },
  { id: 38, spawnTime: 107, originFloor: 2, destinationFloor: 7 },
  { id: 39, spawnTime: 110, originFloor: 9, destinationFloor: 3 },
  { id: 40, spawnTime: 113, originFloor: 4, destinationFloor: 8 },
  { id: 41, spawnTime: 116, originFloor: 0, destinationFloor: 6 },
  { id: 42, spawnTime: 119, originFloor: 6, destinationFloor: 2 },
  { id: 43, spawnTime: 122, originFloor: 3, destinationFloor: 5 },
  { id: 44, spawnTime: 125, originFloor: 8, destinationFloor: 1 },
  { id: 45, spawnTime: 128, originFloor: 5, destinationFloor: 9 },
  { id: 46, spawnTime: 131, originFloor: 2, destinationFloor: 0 },
  { id: 47, spawnTime: 134, originFloor: 7, destinationFloor: 2 },
  { id: 48, spawnTime: 137, originFloor: 1, destinationFloor: 8 },
  { id: 49, spawnTime: 140, originFloor: 9, destinationFloor: 5 },
  { id: 50, spawnTime: 143, originFloor: 4, destinationFloor: 7 },
];
