// src/ai/passenger-scenarios.ts
// 개발자 참고: 새로운 승객 시나리오를 생성할 때, 특정 층에 승객이 과도하게 몰리지 않도록 (예: 동시에 15명 이상 대기) 고려하여 분산시켜주세요.
import type { Person } from '@/hooks/useElevatorSimulation';

// This type is exported for use in other files
export type PassengerManifest = Omit<Person, 'pickupTime'>[];

const normalScenario: PassengerManifest = [
  { id: 1, spawnTime: 4, originFloor: 1, destinationFloor: 8 },
  { id: 2, spawnTime: 6, originFloor: 8, destinationFloor: 2 },
  { id: 3, spawnTime: 10, originFloor: 9, destinationFloor: 1 },
  { id: 4, spawnTime: 13, originFloor: 5, destinationFloor: 2 },
  { id: 5, spawnTime: 16, originFloor: 0, destinationFloor: 7 },
  { id: 6, spawnTime: 18, originFloor: 2, destinationFloor: 6 },
  { id: 7, spawnTime: 21, originFloor: 5, destinationFloor: 9 },
  { id: 8, spawnTime: 26, originFloor: 7, destinationFloor: 3 },
  { id: 9, spawnTime: 29, originFloor: 3, destinationFloor: 0 },
  { id: 10, spawnTime: 31, originFloor: 5, destinationFloor: 0 },
  { id: 11, spawnTime: 35, originFloor: 0, destinationFloor: 9 },
  { id: 12, spawnTime: 39, originFloor: 2, destinationFloor: 7 },
  { id: 13, spawnTime: 42, originFloor: 8, destinationFloor: 3 },
  { id: 14, spawnTime: 44, originFloor: 3, destinationFloor: 6 },
  { id: 15, spawnTime: 49, originFloor: 6, destinationFloor: 0 },
  { id: 16, spawnTime: 53, originFloor: 1, destinationFloor: 5 },
  { id: 17, spawnTime: 57, originFloor: 4, destinationFloor: 8 },
  { id: 18, spawnTime: 59, originFloor: 7, destinationFloor: 4 },
  { id: 19, spawnTime: 61, originFloor: 2, destinationFloor: 5 },
  { id: 20, spawnTime: 66, originFloor: 9, destinationFloor: 4 },
  { id: 21, spawnTime: 69, originFloor: 0, destinationFloor: 6 },
  { id: 22, spawnTime: 71, originFloor: 4, destinationFloor: 1 },
  { id: 23, spawnTime: 75, originFloor: 6, destinationFloor: 3 },
  { id: 24, spawnTime: 79, originFloor: 9, destinationFloor: 0 },
  { id: 25, spawnTime: 82, originFloor: 1, destinationFloor: 7 },
  { id: 26, spawnTime: 86, originFloor: 3, destinationFloor: 8 },
  { id: 27, spawnTime: 91, originFloor: 7, destinationFloor: 2 },
  { id: 28, spawnTime: 94, originFloor: 2, destinationFloor: 9 },
  { id: 29, spawnTime: 96, originFloor: 5, destinationFloor: 1 },
  { id: 30, spawnTime: 99, originFloor: 8, destinationFloor: 4 },
  { id: 31, spawnTime: 104, originFloor: 0, destinationFloor: 5 },
  { id: 32, spawnTime: 107, originFloor: 4, destinationFloor: 7 },
  { id: 33, spawnTime: 110, originFloor: 6, destinationFloor: 2 },
  { id: 34, spawnTime: 114, originFloor: 3, destinationFloor: 9 },
  { id: 35, spawnTime: 116, originFloor: 9, destinationFloor: 5 },
  { id: 36, spawnTime: 121, originFloor: 1, destinationFloor: 6 },
  { id: 37, spawnTime: 125, originFloor: 5, destinationFloor: 3 },
  { id: 38, spawnTime: 127, originFloor: 8, destinationFloor: 1 },
  { id: 39, spawnTime: 132, originFloor: 2, destinationFloor: 7 },
  { id: 40, spawnTime: 135, originFloor: 7, destinationFloor: 0 },
  { id: 41, spawnTime: 139, originFloor: 4, destinationFloor: 9 },
  { id: 42, spawnTime: 142, originFloor: 0, destinationFloor: 8 },
  { id: 43, spawnTime: 147, originFloor: 6, destinationFloor: 4 },
  { id: 44, spawnTime: 151, originFloor: 3, destinationFloor: 5 },
  { id: 45, spawnTime: 153, originFloor: 9, destinationFloor: 2 },
  { id: 46, spawnTime: 157, originFloor: 5, destinationFloor: 0 },
  { id: 47, spawnTime: 161, originFloor: 1, destinationFloor: 4 },
  { id: 48, spawnTime: 166, originFloor: 7, destinationFloor: 1 },
  { id: 49, spawnTime: 168, originFloor: 4, destinationFloor: 6 },
  { id: 50, spawnTime: 172, originFloor: 8, destinationFloor: 0 },
];

const morningRushScenario: PassengerManifest = [
  { id: 1, spawnTime: 1, originFloor: 0, destinationFloor: 7 },
  { id: 2, spawnTime: 2, originFloor: 0, destinationFloor: 5 },
  { id: 3, spawnTime: 2, originFloor: 0, destinationFloor: 9 },
  { id: 4, spawnTime: 3, originFloor: 0, destinationFloor: 4 },
  { id: 5, spawnTime: 4, originFloor: 0, destinationFloor: 6 },
  { id: 6, spawnTime: 5, originFloor: 0, destinationFloor: 8 },
  { id: 7, spawnTime: 6, originFloor: 2, destinationFloor: 5 },
  { id: 8, spawnTime: 7, originFloor: 0, destinationFloor: 3 },
  { id: 9, spawnTime: 7, originFloor: 0, destinationFloor: 7 },
  { id: 10, spawnTime: 8, originFloor: 0, destinationFloor: 2 },
  { id: 11, spawnTime: 9, originFloor: 0, destinationFloor: 9 },
  { id: 12, spawnTime: 10, originFloor: 0, destinationFloor: 5 },
  { id: 13, spawnTime: 11, originFloor: 0, destinationFloor: 6 },
  { id: 14, spawnTime: 12, originFloor: 0, destinationFloor: 3 },
  { id: 15, spawnTime: 14, originFloor: 1, destinationFloor: 9 },
  { id: 16, spawnTime: 15, originFloor: 0, destinationFloor: 8 },
  { id: 17, spawnTime: 15, originFloor: 0, destinationFloor: 4 },
  { id: 18, spawnTime: 16, originFloor: 0, destinationFloor: 7 },
  { id: 19, spawnTime: 17, originFloor: 0, destinationFloor: 2 },
  { id: 20, spawnTime: 19, originFloor: 0, destinationFloor: 6 },
  { id: 21, spawnTime: 20, originFloor: 0, destinationFloor: 5 },
  { id: 22, spawnTime: 22, originFloor: 0, destinationFloor: 9 },
  { id: 23, spawnTime: 23, originFloor: 0, destinationFloor: 4 },
  { id: 24, spawnTime: 25, originFloor: 3, destinationFloor: 8 },
  { id: 25, spawnTime: 26, originFloor: 0, destinationFloor: 7 },
  { id: 26, spawnTime: 28, originFloor: 0, destinationFloor: 3 },
  { id: 27, spawnTime: 30, originFloor: 0, destinationFloor: 8 },
  { id: 28, spawnTime: 32, originFloor: 0, destinationFloor: 1 },
  { id: 29, spawnTime: 33, originFloor: 0, destinationFloor: 9 },
  { id: 30, spawnTime: 35, originFloor: 0, destinationFloor: 6 },
  { id: 31, spawnTime: 38, originFloor: 0, destinationFloor: 4 },
  { id: 32, spawnTime: 40, originFloor: 0, destinationFloor: 5 },
  { id: 33, spawnTime: 43, originFloor: 0, destinationFloor: 2 },
  { id: 34, spawnTime: 45, originFloor: 0, destinationFloor: 8 },
  { id: 35, spawnTime: 48, originFloor: 4, destinationFloor: 7 },
  { id: 36, spawnTime: 52, originFloor: 0, destinationFloor: 9 },
  { id: 37, spawnTime: 55, originFloor: 0, destinationFloor: 3 },
  { id: 38, spawnTime: 59, originFloor: 0, destinationFloor: 6 },
  { id: 39, spawnTime: 62, originFloor: 0, destinationFloor: 7 },
  { id: 40, spawnTime: 65, originFloor: 1, destinationFloor: 4 },
  { id: 41, spawnTime: 70, originFloor: 0, destinationFloor: 5 },
  { id: 42, spawnTime: 74, originFloor: 0, destinationFloor: 8 },
  { id: 43, spawnTime: 78, originFloor: 0, destinationFloor: 2 },
  { id: 44, spawnTime: 83, originFloor: 2, destinationFloor: 9 },
  { id: 45, spawnTime: 88, originFloor: 0, destinationFloor: 9 },
  { id: 46, spawnTime: 94, originFloor: 0, destinationFloor: 3 },
  { id: 47, spawnTime: 100, originFloor: 0, destinationFloor: 7 },
  { id: 48, spawnTime: 106, originFloor: 5, destinationFloor: 8 },
  { id: 49, spawnTime: 112, originFloor: 0, destinationFloor: 6 },
  { id: 50, spawnTime: 120, originFloor: 0, destinationFloor: 4 },
];

const eveningRushScenario: PassengerManifest = [
  { id: 1, spawnTime: 5, originFloor: 8, destinationFloor: 4 },
  { id: 2, spawnTime: 10, originFloor: 9, destinationFloor: 0 },
  { id: 3, spawnTime: 12, originFloor: 7, destinationFloor: 0 },
  { id: 4, spawnTime: 14, originFloor: 5, destinationFloor: 0 },
  { id: 5, spawnTime: 15, originFloor: 6, destinationFloor: 0 },
  { id: 6, spawnTime: 17, originFloor: 8, destinationFloor: 0 },
  { id: 7, spawnTime: 18, originFloor: 4, destinationFloor: 0 },
  { id: 8, spawnTime: 20, originFloor: 3, destinationFloor: 0 },
  { id: 9, spawnTime: 22, originFloor: 9, destinationFloor: 0 },
  { id: 10, spawnTime: 24, originFloor: 2, destinationFloor: 0 },
  { id: 11, spawnTime: 25, originFloor: 7, destinationFloor: 0 },
  { id: 12, spawnTime: 27, originFloor: 5, destinationFloor: 2 },
  { id: 13, spawnTime: 29, originFloor: 6, destinationFloor: 0 },
  { id: 14, spawnTime: 31, originFloor: 4, destinationFloor: 0 },
  { id: 15, spawnTime: 33, originFloor: 8, destinationFloor: 0 },
  { id: 16, spawnTime: 34, originFloor: 3, destinationFloor: 0 },
  { id: 17, spawnTime: 36, originFloor: 9, destinationFloor: 0 },
  { id: 18, spawnTime: 38, originFloor: 1, destinationFloor: 0 },
  { id: 19, spawnTime: 40, originFloor: 7, destinationFloor: 0 },
  { id: 20, spawnTime: 41, originFloor: 5, destinationFloor: 0 },
  { id: 21, spawnTime: 43, originFloor: 6, destinationFloor: 0 },
  { id: 22, spawnTime: 45, originFloor: 2, destinationFloor: 0 },
  { id: 23, spawnTime: 47, originFloor: 8, destinationFloor: 0 },
  { id: 24, spawnTime: 48, originFloor: 4, destinationFloor: 0 },
  { id: 25, spawnTime: 50, originFloor: 9, destinationFloor: 5 },
  { id: 26, spawnTime: 52, originFloor: 3, destinationFloor: 0 },
  { id: 27, spawnTime: 54, originFloor: 7, destinationFloor: 0 },
  { id: 28, spawnTime: 55, originFloor: 1, destinationFloor: 0 },
  { id: 29, spawnTime: 57, originFloor: 6, destinationFloor: 0 },
  { id: 30, spawnTime: 59, originFloor: 8, destinationFloor: 0 },
  { id: 31, spawnTime: 61, originFloor: 2, destinationFloor: 0 },
  { id: 32, spawnTime: 62, originFloor: 5, destinationFloor: 0 },
  { id: 33, spawnTime: 64, originFloor: 9, destinationFloor: 0 },
  { id: 34, spawnTime: 66, originFloor: 4, destinationFloor: 0 },
  { id: 35, spawnTime: 68, originFloor: 7, destinationFloor: 0 },
  { id: 36, spawnTime: 70, originFloor: 3, destinationFloor: 0 },
  { id: 37, spawnTime: 71, originFloor: 6, destinationFloor: 0 },
  { id: 38, spawnTime: 73, originFloor: 8, destinationFloor: 0 },
  { id: 39, spawnTime: 75, originFloor: 1, destinationFloor: 0 },
  { id: 40, spawnTime: 77, originFloor: 9, destinationFloor: 3 },
  { id: 41, spawnTime: 79, originFloor: 5, destinationFloor: 0 },
  { id: 42, spawnTime: 81, originFloor: 2, destinationFloor: 0 },
  { id: 43, spawnTime: 83, originFloor: 7, destinationFloor: 0 },
  { id: 44, spawnTime: 85, originFloor: 4, destinationFloor: 0 },
  { id: 45, spawnTime: 88, originFloor: 8, destinationFloor: 0 },
  { id: 46, spawnTime: 91, originFloor: 6, destinationFloor: 0 },
  { id: 47, spawnTime: 94, originFloor: 3, destinationFloor: 0 },
  { id: 48, spawnTime: 98, originFloor: 9, destinationFloor: 0 },
  { id: 49, spawnTime: 102, originFloor: 5, destinationFloor: 0 },
  { id: 50, spawnTime: 105, originFloor: 7, destinationFloor: 0 },
];

export const passengerScenarios = [
    {
        name: '일반',
        manifest: normalScenario,
    },
    {
        name: '아침 출근 시간',
        manifest: morningRushScenario,
    },
    {
        name: '저녁 퇴근 시간',
        manifest: eveningRushScenario,
    }
];
