import type { Person } from '@/hooks/useElevatorSimulation';

// This manifest defines a fixed sequence of passenger arrivals for the competition.
// Every simulation run will use this exact same data, ensuring fairness.
// - id: Unique identifier for the person.
// - spawnTime: The simulation tick at which the person appears.
// - originFloor: The floor where the person starts waiting.
// - destinationFloor: The floor the person wants to go to.
export const PASSENGER_MANIFEST: Omit<Person, 'pickupTime'>[] = [
  { id: 1, spawnTime: 4, originFloor: 1, destinationFloor: 8 },
  { id: 2, spawnTime: 6, originFloor: 8, destinationFloor: 2 },
  { id: 3, spawnTime: 10, originFloor: 9, destinationFloor: 1 },
  { id: 4, spawnTime: 13, originFloor: 5, destinationFloor: 2 },
  { id: 5, spawnTime: 16, originFloor: 0, destinationFloor: 7 },
  { id: 6, spawnTime: 18, originFloor: 2, destinationFloor: 6 },
  { id: 7, spawnTime: 21, originFloor: 5, destinationFloor: 9 },
  { id: 8, spawnTime: 26, originFloor: 7, destinationFloor: 3 },
  { id: 9, spawnTime: 29, originFloor: 3, destinationFloor: 0 },
  { id: 10, spawnTime: 31, originFloor: 5, destinationFloor: 0 },
  { id: 11, spawnTime: 35, originFloor: 0, destinationFloor: 9 },
  { id: 12, spawnTime: 39, originFloor: 2, destinationFloor: 7 },
  { id: 13, spawnTime: 42, originFloor: 8, destinationFloor: 3 },
  { id: 14, spawnTime: 44, originFloor: 3, destinationFloor: 6 },
  { id: 15, spawnTime: 49, originFloor: 6, destinationFloor: 0 },
  { id: 16, spawnTime: 53, originFloor: 1, destinationFloor: 5 },
  { id: 17, spawnTime: 57, originFloor: 4, destinationFloor: 8 },
  { id: 18, spawnTime: 59, originFloor: 7, destinationFloor: 4 },
  { id: 19, spawnTime: 61, originFloor: 2, destinationFloor: 5 },
  { id: 20, spawnTime: 66, originFloor: 9, destinationFloor: 4 },
  { id: 21, spawnTime: 69, originFloor: 0, destinationFloor: 6 },
  { id: 22, spawnTime: 71, originFloor: 4, destinationFloor: 1 },
  { id: 23, spawnTime: 75, originFloor: 6, destinationFloor: 3 },
  { id: 24, spawnTime: 79, originFloor: 9, destinationFloor: 0 },
  { id: 25, spawnTime: 82, originFloor: 1, destinationFloor: 7 },
  { id: 26, spawnTime: 86, originFloor: 3, destinationFloor: 8 },
  { id: 27, spawnTime: 91, originFloor: 7, destinationFloor: 2 },
  { id: 28, spawnTime: 94, originFloor: 2, destinationFloor: 9 },
  { id: 29, spawnTime: 96, originFloor: 5, destinationFloor: 1 },
  { id: 30, spawnTime: 99, originFloor: 8, destinationFloor: 4 },
  { id: 31, spawnTime: 104, originFloor: 0, destinationFloor: 5 },
  { id: 32, spawnTime: 107, originFloor: 4, destinationFloor: 7 },
  { id: 33, spawnTime: 110, originFloor: 6, destinationFloor: 2 },
  { id: 34, spawnTime: 114, originFloor: 3, destinationFloor: 9 },
  { id: 35, spawnTime: 116, originFloor: 9, destinationFloor: 5 },
  { id: 36, spawnTime: 121, originFloor: 1, destinationFloor: 6 },
  { id: 37, spawnTime: 125, originFloor: 5, destinationFloor: 3 },
  { id: 38, spawnTime: 127, originFloor: 8, destinationFloor: 1 },
  { id: 39, spawnTime: 132, originFloor: 2, destinationFloor: 7 },
  { id: 40, spawnTime: 135, originFloor: 7, destinationFloor: 0 },
  { id: 41, spawnTime: 139, originFloor: 4, destinationFloor: 9 },
  { id: 42, spawnTime: 142, originFloor: 0, destinationFloor: 8 },
  { id: 43, spawnTime: 147, originFloor: 6, destinationFloor: 4 },
  { id: 44, spawnTime: 151, originFloor: 3, destinationFloor: 5 },
  { id: 45, spawnTime: 153, originFloor: 9, destinationFloor: 2 },
  { id: 46, spawnTime: 157, originFloor: 5, destinationFloor: 0 },
  { id: 47, spawnTime: 161, originFloor: 1, destinationFloor: 4 },
  { id: 48, spawnTime: 166, originFloor: 7, destinationFloor: 1 },
  { id: 49, spawnTime: 168, originFloor: 4, destinationFloor: 6 },
  { id: 50, spawnTime: 172, originFloor: 8, destinationFloor: 0 },
];
